services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pakistan-chatbot-backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pakistan-chatbot-frontend
    restart: always
    ports:
      - "8095:80"
    depends_on:
      - backend
